"""
A container for containing both an electorate and the seed that generated it.
"""
struct SeededElectorate <: AbstractMatrix{Float64}
    data::Matrix{Float64}
    seed::Int
end

"""
Contains an electorate generated by a spatial model.

voter_coordinates[k, i] is where voter i stands on dimension k.
caring_matrix[k, i] is how much voter i cares about dimension k.
candidate_coordinates[k, j] is where candidate j stands on dimension k.
utility_matrix[i, j] is how much voter i likes candidate j.
seed is the random seed used to generate the electorate.
"""
struct SpatialElectorate
    voter_coordinates::Matrix{Float64}
    caring_matrix::Matrix{Float64}
    candidate_coordinates::Matrix{Float64}
    utility_matrix::Matrix{Float64}
    seed::Int
end

"""
An electorate and associated information

voter_coordinates[k, i] is where voter i stands on dimension k.
caring_matrix[k, i] is how much voter i cares about dimension k.
candidate_coordinates[k, j] is where candidate j stands on dimension k.
utility_matrix[i, j] is how much voter i likes candidate j.
intercandidate_utility_matrix[i, j] is how much candidate j likes candidate i.
candidate_qualities[i] is how "good" candidate i is, in a sense that every voter agrees on.
seed is the random seed used to generate the electorate.
"""
struct AugmentedElectorate <: AbstractMatrix{Float64}
    voter_coordinates::Matrix{Float64}
    caring_matrix::Matrix{Float64}
    candidate_coordinates::Matrix{Float64}
    utility_matrix::Matrix{Float64}
    intercandidate_utility_matrix::Matrix{Float64}
    candidate_qualities::Vector{Float64}
    seed::Int
end

Base.size(e::AugmentedElectorate) = size(e.utility_matrix)
Base.getindex(e::AugmentedElectorate, I::Vararg{Int,N}) where {N} = e.utility_matrix[I...]
Base.setindex!(e::AugmentedElectorate, v::Float64, I::Vararg{Int,N}) where N = (e.utility_matrix[I...] = v)
getseed(e::AugmentedElectorate) = e.seed

function SpatialElectorate(vc::Matrix{Float64}, cm::Matrix{Float64}, cc::Matrix{Float64}, seed::Int)
    um = make_utility_matrix(vc, cm, cc)
    SpatialElectorate(vc, cm, cc, um, seed)
end

Base.size(e::SeededElectorate) = size(e.data)
Base.getindex(e::SeededElectorate, I::Vararg{Int,N}) where {N} = e.data[I...]
Base.setindex!(e::SeededElectorate, v::Float64, I::Vararg{Int,N}) where N = (e.data[I...] = v)
getseed(e::SeededElectorate) = e.seed
getseed(::Any) = 0